### ISSUE TITLE
Articulate doesn't seem to interface with Arma 3.

### ISSUE THREAD

**Issue by ctrsnarebear** [Mpstark/articulate#92]
Arma 3 acts like Articulate is not working, even though Articulate seems to be working.

I think I've done everything right.
1. Used the ArticulateSetup.exe installer - it said that my OS (Windows 10) already has the .Net 4.5 framework installed.
2. I run Arma 3 from Steam, so it doesn't run as an admin. I didn't run Articulate as admin either (for kicks I tried running Articulate as admin too, but it didn't change anything).
3. Articulate recognizes my voice (I did the Windows Voice Recognition Training), and it shows that it recognizes that I'm giving it valid commands (e.g. I say "One, Two, Move up!" and it shows " one, two, move up" on the Articulate GUI.
3. I run both Arma 3 (from Steam) and Articulate (from my desktop shortcut).
4. Nothing happens in Arma 3 when I give commands as group leader. It's as if Articulate doesn't exist.

What am I missing? Thank you for your consideration.

**Comment by SPARTAN563** [comment]
Hi @ctrsnarebear - quick question, are you running the original ArmA 3 keybindings or the revised Apex ones? (i.e. do the F1-F10 keys select squad members or not).
Unfortunately Articulate was developed prior to Apex and never gained the ability to customise ones key bindings. We've seen a similar issue in #88 and the fix is either to switch to the standard ArmA 3 keybindings or to re-compile Articulate with a modified command set yourself.

**Comment by ctrsnarebear** [comment]
Thanks so much for your reply. I _**really**_ love the idea of Articulate, and I hope I can get it working. 

I have never switched to Apex keybindings. I have a lot of custom keybindings, but I have never touched the squad command keybindings. So the F1-F10 keys **_are_** the ones that select squad members.

You don't suppose ACE3 could be interfering somehow, do you?

**Comment by SPARTAN563** [comment]
No worries, okay that sounds like it should be working then. One other potential issue is permissions, can you try running Articulate as administrator perhaps and see if that solves the issue? If you've got two screens, keep Articulate running on the second and see if it actually recognised your command or not - I'm just trying to figure out if it's struggling to send key messages to ArmA 3 by any chance.

I don't think ACE3 should be interfering, I used to run ACE3 with it and never had any issues (but this was a while ago now).

**Comment by ctrsnarebear** [comment]
I did try running it as administrator (even though I don't think Steam runs programs as administrator), but no luck. I don't have two screens, but I did Alt+Tab out of Arma 3 to make sure that Articulate was working (it is - it shows the command that I just said). But it's like Arma 3 isn't getting the message.

I also tried using the previous version of Articulate, but there was no change. I installed and uninstalled Articulate several times too. I'm not sure what else to try... maybe I should try disabling mods. The only mod I have that changes how the game works is ACE3 (and CBA, of course) - everything else is just content (weapons, vehicles, etc.). Sorry I'm not more tech savvy. Thanks again for your patience in dealing with my issue.

**Comment by SPARTAN563** [comment]
Huh, that's really odd, if you wouldn't mind trying without mods - I'm not holding out hope for that fixing the issue, but if it does then that's a good data point. I'm currently at the office unfortunately, but when I get home I'll try and reproduce your issue and (if I can) put together a fix for you.

It might also have something to do with ArmA's recent change from 32-bit to 64-bit executables, but that's just me thumb-sucking ideas right now, I'll need to do some more work to confirm that.

**Comment by ctrsnarebear** [comment]
I tried disabling all my mods, but no luck.

**Comment by ctrsnarebear** [comment]
I tried making a new profile, so that I could be sure it wasn't a keybinding issue. Still no luck.

**Comment by SPARTAN563** [comment]
Hi @ctrsnarebear, I've been testing this out and for the life of me can't figure out why it isn't working for you. I spun up the latest version of Articulate on my machine, opened ArmA 3 and started giving orders with absolutely no issues whatsoever. I am running the latest dev build (1.73), but I doubt that has anything to do with it.

Just an idea, do you have some kind of on screen overlay or recording software running? Articulate checks what the currently active foreground window is and will only send events if that window is ArmA. If for some reason there's an overlay that is stealing focus and forwarding events underneath it, then Articulate won't be sending events through (the UI should probably indicate this, but it doesn't right now).

Unfortunately the only way to know for sure is to attach a debugger to Articulate and look at the output it produces, if you really want to go down that rabbit hole then [VS Community Edition](https://www.visualstudio.com/vs/community/) is free and will allow you to do just that.

**Comment by Ca11SignPatriot** [comment]
I am having the same problem. What are the source code files? Do I need them if i downloaded the installer?

**Comment by SPARTAN563** [comment]
You shouldn't need the source code if you've downloaded the binary (installer), however if you want to build it yourself then you will need them.

**Comment by Ca11SignPatriot** [comment]
Okay, I did download the installer, however the voice commands still wont work on arma.

**Comment by Ca11SignPatriot** [comment]
Could you maybe post or link a manual instillation video so me and ctrsnarebear can make sure theres no problem on our part or so we can make sure its not a problem with the auto-installer?

**Comment by ctrsnarebear** [comment]
I feel a little less idiotic knowing I have a comrade in confusion (Hi, Ca11SignPatriot!).

To my knowledge, I am not running any such overlay or recording software (and I'm pretty sure I would know). I've been playing Arma 3 on my Dell Inspiron laptop - I'm lucky to get 30 FPS on 80% sampling and practically everything else set to "low" or "off." I can just imagine what would happen if I tried running recording software. I also just did a reinstall of Windows 10, so I doubt it's an issue with a bloatware program I'm not aware of.

Steam does have an in-game overlay feature. I have it disabled though. Is it possible that it's not really turned off (just inaccessible from in-game)? I should try running Arma 3 without Steam... never tried that before, or even considered that it was possible, though now that I think about it, why shouldn't it be?

I am swamped for the rest of the week, but I will try to get it working on Saturday and attach the debugger. As always, thanks again for your patience with this issue.

**Comment by ctrsnarebear** [comment]
So, the Visual Studio stuff is way over my head. I don't even know where to start. I tried disabling the Microsoft game bar, but that didn't help anything. Thanks anyways.

**Comment by joeynuggetz** [comment]
Same issue here. After jumping thru hoops trying to get everything that was trying to tell me this software was a virus to ignore it, I have it installed and running and it recognizes commands and plays souinds but has 0 effect in Arma 3. Running windows 10 here too.

**Comment by joeynuggetz** [comment]
By the way I used the installer and already had the.net stuff installed so it skipped that. Im running the 64 bit arma. Could it be that? Is there anything else I can provide to help figure out why it's not working. Didn't know this existed and was the answer to all of my problems and it's a shame it doesn't work for me.

**Comment by joeynuggetz** [comment]
Yep. that was it. If you run the 64 bit version of Arma via the launcher then the exe that is spawned is Arma_64.exe. Can you guys fix this so I can run the 64 bit version? Please?

**Comment by SPARTAN563** [comment]
Hey @joeynuggetz - can you quickly confirm that the executable name you're seeing is in fact `Arma_64.exe` rather than `arma3_x64.exe`? As you can see [here](https://github.com/Mpstark/articulate/blob/master/Articulate/MainWindow.xaml.cs#L201) we're currently looking for the latter, so if the former is in your installation (which must be different to mine then) then it's a relatively quick fix.

**Comment by joeynuggetz** [comment]
Actually, no you are correct. When running in 64bit mode, the process is indeed called arma3_x64.exe. Why the heck is it working in 32 bit mode and not 64. Thats strange. There was a big update pushed out and I didn't try 64bit yet as I had just tried last night. Will give X64 another test then. This is strange.

**Comment by SPARTAN563** [comment]
How very odd, I tell you what, is there any chance you had an older version of Articulate installed at any point? If so, can you try removing `%AppData%\Roaming\Articulate\config.dat` and see if that solves your problems? There's a small chance that you had a config that didn't include the `x64` executable in the supported list.

Honestly though, I suspect the chances of that being the issue are pretty low, but if you guys are willing to try something out, I can send one of you a version that reports metrics on which application is in the foreground when you say a command. I don't want to generally release that since it does represent a bit of a privacy risk, but for some quick diagnostics it'd be incredibly useful.

**Comment by SPARTAN563** [comment]
Hi everyone, I'm terribly sorry that it's taken this long to track down, but thanks to the awesome help of @joeynuggetz I think we've got a fix. Long story short, this appears to be an issue facing people who run the 64-bit version of ArmA 3 but who previously ran a version of Articulate older than v0.2.12 and did not remove their configuration file after the update.

I've released [v0.2.13](https://github.com/Mpstark/articulate/releases/tag/v0.2.13) which automates the update process for the configuration file and should resolve any issues you've been facing, but of course, if that doesn't fix it please let me know and I'll continue trying to address the issues you're facing.

You can download the latest [v0.2.13](https://github.com/Mpstark/articulate/releases/tag/v0.2.13) installer here: [v0.2.13](https://github.com/Mpstark/articulate/releases/tag/v0.2.13).

**Comment by ctrsnarebear** [comment]
I installed the new version using the installer, but had the same problem. The situation you describe (running the old version and not removing config files) doesn't apply to me. I don't think the 64-bit version does either, as I understand the 64-bit version is still only on dev branch.

The only difference I noticed was that before, my antivirus (Avast) did not want me to even download the installer, let alone run it. This time, it also got all bothered when I tried to run Articulate (after install).

**Comment by ctrsnarebear** [comment]
IT'S WORKING.

The fact that Avast didn't like even running the program this time gave me the idea to disable its File System Shield and its Behavior Shield. After that, it didn't give me any problems starting Articulate, and it worked just fine (when it understood me - I'm using a set of earbuds with an in-line mic right now, but that's not Articulate's fault). I could even turn the System Shield and Behavior Shield back on, and Articulate continued to work (though I didn't test this for an extended period of time).

So after all that, the problem turns out to be one you already know about - that antivirus software thinks Articulate is malicious. Mind if I send the setup file to Avast and ask them to whitelist it?

**Comment by joeynuggetz** [comment]
Yeah, one does have to go thru hoops just to get this software to run.  Glad you got it working. BTW, the 64 bit version of Arma appears to be the default for me so I dont think it s a dev branch only thing.

![image](https://user-images.githubusercontent.com/14797846/27490730-02cc9c12-5805-11e7-953d-6be9a63c6697.png)

**Comment by ctrsnarebear** [comment]
Oh I see. I just didn't notice the Platform option in the Parameters tab. Looks like I was running 64-bit all along though.

**Comment by Baraz-Siriel** [comment]
I run _Articulate_ with ARMA 3 64bits version and, since it simply uses the Windows voice recognition, it should run without any issues.  

The most logical reason I can see why it would not work is the default Command keybind which is **`** (sometimes **/**) (the key to the left of 1).  In the keybinding menu, set it back to default and do the same for other Command keybindings, checking if they game notes any keybind conflicts.

**Comment by notheotherben** [comment]
Hi @Baraz-Siriel - there's two possible issues, the first is that you're using the new keybinding layout for ArmA 3 (which uses `Shift+[x]` for command selection), while the second is that you've got an antivirus which is preventing Articulate from passing commands to the ArmA 3 executable.

In the former case, the quick solution is to switch to the legacy ArmA 3 keybinds, while in the latter you'll want to whitelist Articulate with your antivirus to ensure it can function correctly.

**Comment by Baraz-Siriel** [comment]
Thank you, but it is not my issue. I was responding to this thread where the last posts were about ARMA3  64 bits: I was stating that this aspect should not have any impact on how Articulate works with the game.  

Therefore, I was suggesting to ctrsnarebear that the problem is most probably just the command keybinds, like you explain.

**Comment by notheotherben** [comment]
Oh, I see, sorry for my misunderstanding and glad to hear that it is working correctly for you :+1:

**Comment by RonBurgundysguns** [comment]
Hi all, just returned to Arma 3 after an 18 month break. used to use this amazing addon all the time. My issue was exactly the same as at the top of the thread. Loading through Steam Launcher, Articulate didn't work within A3 only etc. 
I tried launching with the arma3.exe directly and it worked without my mods), so I found this thread. 
Updated my version or Articulate just now and it works through Steam. Big thanks!
I recently moved my entire Steam folder out of program files folder, so i thought that was the issue at first. I take it that doesn't make a difference to Articulate then?

**Comment by ChrisBockus** [comment]
Hi All, just wanted to start by saying amazing job with this application. This is really impressive and I appreciate that you've shared (along with the source code!).  I've drastically remapped my keybindings from the default settings and was wondering if you could point me in the right direction as to where in the source code I'd go to edit.  I'm new to C# but have experience with other languages (python, vba). I am going to download visual studio this weekend and see if I can figure it out for myself. Just wanted to check if you had any suggestions ahead of time. 

Any insight you could provide would be greatly appreciated.  Thank you!

**Comment by notheotherben** [comment]
Of course, you're going to want to take a look at the following file:

https://github.com/Mpstark/articulate/blob/master/Articulate/Components/CommandPool.cs

You'll notice that commands there fall under a number of areas and in each case there is a `DirectInputEmulator.KeyPress(...)` call associated with the command. That should get you most of the way to creating your own key-map implementation. Good luck 👍

**Comment by ChrisBockus** [comment]
This is exactly what I was looking for, thanks again. Really appreciate the help.
